# Generated by Django 4.2.1 on 2024-04-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('age', models.IntegerField(null=True)),
                ('sex', models.BooleanField(default=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('regdate', models.DateField()),
            ],
        ),
    ]
