# Generated by Django 4.2.1 on 2024-04-12 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_alter_movie_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='cover_image',
        ),
    ]
