# Generated by Django 4.2.1 on 2024-04-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_remove_movie_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.CharField(default='', max_length=255),
        ),
    ]
