# Generated by Django 4.2.1 on 2024-04-13 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0008_alter_movie_movie_id_alter_screeningroom_room_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='paytime',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='img',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='showtime',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
