# Generated by Django 4.2.1 on 2024-04-13 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0009_ticket_paytime_alter_movie_img_alter_ticket_showtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='screeningroom',
            name='price',
            field=models.IntegerField(default=100),
        ),
    ]
