# Generated by Django 4.2.1 on 2024-04-13 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0011_alter_ticket_evaluation_alter_ticket_paytime'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='paystatus',
            field=models.BooleanField(default=False),
        ),
    ]
